"""Add plaid_item_id to User model

Revision ID: 0dc392aea311
Revises: f22b46ee3b4f
Create Date: 2024-10-22 21:12:57.354890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc392aea311'
down_revision: Union[str, None] = 'f22b46ee3b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plaid_item_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plaid_item_id')
    # ### end Alembic commands ###
