"""Add plaid_user_token to users

Revision ID: f22b46ee3b4f
Revises: 21998c8c1341
Create Date: 2024-10-22 20:24:32.571027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f22b46ee3b4f'
down_revision: Union[str, None] = '21998c8c1341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plaid_user_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plaid_user_token')
    # ### end Alembic commands ###
